version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - "5000"
    env_file:
      - ./.env.prod
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        flask db upgrade
        uwsgi envs/uwsgi/app.ini
    links:
      - db
    depends_on:
      - db
  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    volumes:
      - ./envs/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend