version: "3.7"

services:
  testdb:
    image: mysql/mysql-server:8.0.23
    expose:
      - "3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: TestDB
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
  backend:
    env_file:
      - ./.env.test