version: "3.7"

services:
  db:
    image: mysql/mysql-server:8.0.23
    expose:
      - "3306"
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ExerciseDB
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
